package-lock.json
package.json
src/app/api/generate-plan/route.ts

> #7 
1. AI 프롬프트 생성 로직 route.ts 구현
2. OPENAI api 키 발급 및 .env.local에 로직 처리
3. openai 패키지 설치 
> UI 변경 등 시각적으로 확인할 수 있는 내용이 있다면 첨부해주세요
> `npm instaill openai` 진행해주세요.
`.env.local` 업데이트 했으니 슬랙 팀 채널 확인해주세요.

[feat] AI 생성 관련 route 구현 

---

src/components/Header.tsx
src/components/LoginForm.tsx

> #6 
>로구인 기능 구현 및 헤더 상태 변경
> <img width="1571" height="844" alt="image" src="https://github.com/user-attachments/assets/8f3e67e1-e009-4c4c-a7b9-9ca5178590ab" />

[feat] 로그인 기능 구현 및 헤더 상태변경

---

package-lock.json
package.json
src/app/community/[id]/CommunityDetail.tsx
src/app/community/[id]/page.tsx
src/app/community/page.tsx
src/types/community.ts

> #8 
-  후기 페이지, 댓글 supabase에서 가져오는 기능
-  댓글 생성 및 저장기능
- types 폴더에 interface 생성
> src폴더 밑에 types폴더에 interface들 모아서 정리하면 좋을 것 같습니다

[feat] 여행 후기 페이지 기능 일부 구현

---

src/app/my-plans/page.tsx
src/components/Header.tsx
src/components/LoginForm.tsx

> #13 
> 로그인 후 헤더 세션 상태 감지 및 갱신 로그아웃 시 쿠키 초기화 
> 소셜로그인 성공시 로딩화면 개선
> <img width="1120" height="696" alt="image" src="https://github.com/user-attachments/assets/e7da652f-0f23-4885-9516-f6391db29597" />

[Fix&Design] 로그인 후 상단바 업데이트 및 소셜로그인 이동페이지 수정 

---

package-lock.json
package.json
src/app/api/plans/[id]/route.ts
src/app/my-plans/[id]/modify/page.tsx
src/app/my-plans/[id]/page.tsx
src/app/my-plans/page.tsx

#31 
> 상세 페이지에 수정 버튼 추가
> 수정 페이지 생성
> 수정된 값 DB에 저장
> 수정된 계획에 맞춰 AI 맞춤 일정 다시 생

[feat] 내 여행 상세 페이지 수정 기능 구현

---

src/app/destinations/[id]/DestinationDetail.tsx

> #37 
> 여행지 세부 페이지의 여행 후기 탭을 슈퍼베이스와 연동하여 데이터를 불러오도록 구현

[feat] 여행지 여행 후기 탭 구현

---

src/app/community/[id]/CommunityDetail.tsx
src/app/community/new/page.tsx
src/app/community/page.tsx

> 후기 페이지에서 로그인 한 유저가 아닌 다른 유저의 uuid를 받는 현상 수정하였습니다.

[fix] 후기 페이지 auth.user 다른 유저의 uuid 받는 버그 수정

---

src/app/destinations/[id]/DestinationDetail.tsx

> #37 
> 여행지의 패키지 탭 Supabase에 데이터 삽입 및 호출 구현
>

[feat] 여행지 패키지 탭 구현

---

src/app/community/[id]/CommunityDetail.tsx
src/types/community.ts

> #8 
> 대댓글 기능 구현
> 부모 댓글 삭제하면 자식 댓글까지 같이 삭제되게 하였습니다.
> 댓글 개수 구하는 로직을 등록시 +1 삭제 시 -1 이렇게 했는데 supabase의 댓글 개수를 count하는 방식으로 변경해야 할 것 같아요

[feat] 대댓글 기능 구현

---

src/components/HeroSection.tsx
src/components/PopularDestinations.tsx

#47 
- 여행지 검색 기능 구현
- 메인 HeroSection 컴포넌트에서 여행지 검색 기능 구현
- 사용자가 여행지명을 입력하면 DB에서 해당 여행지를 검색하여, 검색 결과가 있으면 해당 여행지 상세페이지로 이동
- 검색 결과가 없을 경우 검색 결과 없음 알림 메시지 출력
> UI 변경 등 시각적으로 확인할 수 있는 내용이 있다면 첨부해주세요
> 패키지 여행 검색은 비효율적이라 기능 및 ui 자체를 삭제했습니다.

[feat] 여행지 검색 기능 구현 

---

src/app/api/plans/[id]/route.ts

X
> Next.js 동적 API Route에서 context.params await 처리하여 에러 해결 (GET, PATCH 모두 적용)
> UI 변경 등 시각적으로 확인할 수 있는 내용이 있다면 첨부해주세요

[fix] Next.js 동기적 params 에러 해결

---

src/app/api/plans/route.ts
src/app/destinations/[id]/DestinationDetail.tsx
src/app/my-plans/page.tsx

> ex) #이슈번호, #이슈번호
> 예약하기 버튼 구현
> <img width="1471" height="719" alt="image" src="https://github.com/user-attachments/assets/91bce0b7-52ee-47a2-9cc1-6e892fa3d7bc" />
>

[Fix] 패키지 탭 예약하기 버그 수정

---

src/app/community/page.tsx

> ex) #8 
>로그인되지 않았을 때 여행후기 페이지 들어가면 로그인 페이지로 가게 설정

[feat] 로그인되지 않았을 때 여행후기 페이지 들어가면 로그인 페이지로 가게 설정

---

src/app/api/plans/[id]/route.ts
src/app/my-plans/[id]/modify/page.tsx
src/app/my-plans/[id]/page.tsx
src/components/MyPlanEditor.tsx

#31 
> ex) #이슈번호, #이슈번호
> 내 계획 상세 페이지 AI생성 일정 수정 기능 추가
> 내 계획 상세 페이지 내 계획 삭제 기능 추
삭제 기능
수정 기능
수정 후

[feat] 내 계획 삭제 기능 및 AI생성 일정 수정 기능 추가

---

src/app/community/new/page.tsx
src/app/community/page.tsx
src/types/community.ts

> ex) #8 
> 후기 페이지 삭제시 storage에 있는 파일도 삭제

[feat] 후기 페이지 삭제시 storage에 있는 파일도 삭제

---

src/app/auth/callback/page.tsx

[Fix] 소셜로그인 관련

---

package-lock.json
package.json
src/components/Features.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/HeroSection.tsx

[Fix] 사이트 이름 변경

---

src/app/community/[id]/CommunityDetail.tsx
src/app/community/new/page.tsx
src/app/community/page.tsx
src/components/CommunityCard.tsx
src/types/community.ts

[refactor] 게시판 페이지 기능 분리 및 변수명 변경

---

package-lock.json
package.json
src/components/HeroSection.tsx
src/components/PopularDestinations.tsx

[Design] 메인페이지 애니메이션

---

src/app/community/[id]/CommunityDetail.tsx

> ex) #87 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요 (이미지 첨부 가능)

[fix] 댓글 삭제시 댓글 개수 바로 반영 안되는 이슈

---

src/app/community/[id]/CommunityDetail.tsx
src/app/community/page.tsx
src/components/Header.tsx

> ex) #89 
> 여행 후기 댓글 시간 보기 편하게 변경 및 삭제 버튼 왼쪽으로 옮김

[design] 여행 후기 댓글 시간 보기 편하게 변경 및 삭제 버튼 왼쪽으로 옮김
